### ISSUE TITLE
MTP Launch

### ISSUE THREAD

**Issue by Sinusealpha** [MedX-Media/MedX#10]
## Responsibility:
@Sinusealpha @aref-asadi 

## Deadline:
22 Aug 2024

## Description
we are gonna launch our mtp (minimum testable product) in the 22 of aug. so we need to have an issue to check all we need for this event!

this is our checklist for the **website**: @aref-asadi 
- [ ] functioning website 
- [ ] users can subscribe to the first writer, who is maybe me, @Sinusealpha.
- [ ] users can read contents.
- [ ] users can see more than 10 contents.
- [ ] users can see the latest content under each post.
- [ ] users can see the footer and header and use their functions.
- [ ] users can share the content on social media.

this is our checklist for the **telegram channel**: @Sinusealpha 
- [x] users can join our channel.
- [ ] users can see at least 50% of each content in our telegram channel.
- [x] users can share our content with their contacts.
- [x] we are prepared to share the content in related channels.
- [ ] our telegram post is beautiful, functioning, and easy to be engaged with.
- [ ] we've posted some content in our telegram channel to not be empty.

this is our checklist for the **session of launching**: @Sinusealpha 
- [x] we prepared all the things we needed to present in this session.
- [x] we prepared the thing we wanted to say about medx in the 10 last minutes of the session.
- [x] we prepared our call to action.
- [ ] we prepared ourselves for after-launch day and have answers for what is coming.

**Comment by aref-asadi** [comment]
Thank you, dear Sina. I will check the checklist and give you my feedback.

**Comment by Sinusealpha** [comment]
> Thank you, dear Sina. I will check the checklist and give you my feedback.

you're very welcome. please mark this checklist as we go, in your section.

**Comment by Sinusealpha** [comment]
you can also add any part you think we should see in this checklisk.

**Comment by aref-asadi** [comment]
# MTP Launch

## Website

- [ ] [Implement Website](https://github.com/MedX-Media/MedX/issues/12) @aref-asadi 
- [ ] Review. @Sinusealpha

**Comment by aref-asadi** [comment]
For Telegram checklist:

- Maybe it's better to have 25% of each content in the channel. My suggestion is an image, a title, a date and time, an author, and a link to the content page on the website.
- My suggestion for engagement in Telegram is just reactions. I think it's better to not have comments and consider that in the website in the future.

For Session of Launching:
Please provide more explanations.

**Comment by Sinusealpha** [comment]
dear @aref-asadi, i don't know how long our content will be. so discussing about the percentage we want to show in our telegram channel is somewhat nonsense! i'm just thinking about (two paragraph under a photo + a link to website) for a typical telegram channel post. what do you think?

not having comment will show us as same as that authoritarian telegram channels where no one can co-lead. so i think your suggestion is on the opposite side of our "open" culture.

**Comment by Sinusealpha** [comment]
i should also add that for launching session, i'm gonna show our website and this org github page directly to the users. all i want to say is that, like sessions's purpose, this website will help your for further exploring and you can also help us in this fun journey! i think after 1.5 h of speaking about latest advances of ai in med, it will be thee best possible cta. what do you think about it?

**Comment by aref-asadi** [comment]
> dear @aref-asadi, i don't know how long our content will be. so discussing about the percentage we want to show in our telegram channel is somewhat nonsense! i'm just thinking about (two paragraph under a photo + a link to website) for a typical telegram channel post. what do you think?
> 
> not having comment will show us as same as that authoritarian telegram channels where no one can co-lead. so i think your suggestion is on the opposite side of our "open" culture.

About the suggestion on Telegram posts template in channel as I said my suggestions are below:
- an image
- a title
- a date and time
- an author
- and a link to the content page on the website

And about the comment section, well I agree with you.

**Comment by aref-asadi** [comment]
> i should also add that for launching session, i'm gonna show our website and this org github page directly to the users. all i want to say is that, like sessions's purpose, this website will help your for further exploring and you can also help us in this fun journey! i think after 1.5 h of speaking about latest advances of ai in med, it will be thee best possible cta. what do you think about it?

I agree with you on this one too.
