### ISSUE TITLE
Video Crafting Principles

### ISSUE THREAD

**Issue by hossein-kazzemi** [MedX-Media/MedX#11]
## Responsibility : 
@hossein-kazzemi 

## First Video Content deadline : 
22 Aug 2024 (1 shahrivar 1403)

## Video crafting System :
- [ ] Day 1 : Write down the content on google docs
- [ ] Day 2 : Review 
- [ ] Day 3 : Create a storyboard
- [ ] Day 4 : Video Crafting
- [ ] Day 5 : Video editing
- [ ] Day 6 : Review
- [ ] Day 7 : Publish

**Comment by Sinusealpha** [comment]
thank you dear @hossein-kazzemi. but do you think that creating a story board is necessary and possible for a "system" of rapid video creating? can you afford it? if yes, please do it one time and tell me the total time we need to make and publish a video.

**Comment by hossein-kazzemi** [comment]
> thank you dear @hossein-kazzemi. but do you think that creating a story board is necessary and possible for a "system" of rapid video creating? can you afford it? if yes, please do it one time and tell me the total time we need to make and publish a video.

Dear @Sinusealpha, story board is not necessary for our **early** contents and we can get it done just by our **imagination** and without write it down so **it does not take any time**, although for our further goals and temptations story board is necessary to maintain our content consistency.

**Comment by Sinusealpha** [comment]
> > thank you dear @hossein-kazzemi. but do you think that creating a story board is necessary and possible for a "system" of rapid video creating? can you afford it? if yes, please do it one time and tell me the total time we need to make and publish a video.
> 
> 
> 
> Dear @Sinusealpha, story board is not necessary for our **early** contents and we can get it done just by our **imagination** and without writing it down so **it does not take any time**, although for our further goals and temptations story board is necessary to maintain our content consistency.   

Is it easy to afford? How long does a video build process from zero to publishing take?

**Comment by hossein-kazzemi** [comment]
> > > thank you dear @hossein-kazzemi. but do you think that creating a story board is necessary and possible for a "system" of rapid video creating? can you afford it? if yes, please do it one time and tell me the total time we need to make and publish a video.
> > 
> > 
> > Dear @Sinusealpha, story board is not necessary for our **early** contents and we can get it done just by our **imagination** and without writing it down so **it does not take any time**, although for our further goals and temptations story board is necessary to maintain our content consistency.
> 
> Is it easy to afford? How long does a video build process from zero to publishing take?

the videos with no camera movement and just talking with camera just takes 2 days. one day for create the video from idea to take the film another day for editing and revising. For videos with more urgency we can make it less than 1 day.

**Comment by Sinusealpha** [comment]
> > > > thank you dear @hossein-kazzemi. but do you think that creating a story board is necessary and possible for a "system" of rapid video creating? can you afford it? if yes, please do it one time and tell me the total time we need to make and publish a video.
> 
> > > 
> 
> > > 
> 
> > > Dear @Sinusealpha, story board is not necessary for our **early** contents and we can get it done just by our **imagination** and without writing it down so **it does not take any time**, although for our further goals and temptations story board is necessary to maintain our content consistency.
> 
> > 
> 
> > Is it easy to afford? How long does a video build process from zero to publishing take?
> 
> 
> 
> the videos with no camera movement and just talking with camera just takes 2 days. one day for create the video from idea to take the film another day for editing and revising. For videos with more urgency we can make it less than 1 day.

tell me in the scale of hours or even minutes. not days! :)

**Comment by Sinusealpha** [comment]
hey @hossein-kazzemi :) how things are going?
