### ISSUE TITLE
website's bugs

### ISSUE THREAD

**Issue by Sinusealpha** [MedX-Media/MedX#15]
## responsibility
@aref-asadi 

## deadline
23 aug (today)

## descriptions

we have to fix these bugs as soon as possible. people are coming to our website and it's not even functional!

these are some of the must-be-fixed things i saw:
- the "بیشتر بخوانید" button doesn't work.
- one of those "پربازدیدترین اخبار" and "تازه‌ترین اخبار" must be deleted.
- header and footer aren't related to what we are. what is that "صفحه کاربری" and youtube button.
- the date of 2 new essays i added should be changed to past.
- medx's logo isn't that we use in other places and it's not even clickable (to go to the home page)

i'm waiting for you to fix it. thank you. :)

**Comment by aref-asadi** [comment]
Thank you for pointing these out. Here’s what I’ve done and what needs clarification:

1. The "بیشتر بخوانید" Button: I’ve tested the "بیشتر بخوانید" button multiple times and it seems to be working fine for me. Could you please provide more details if you’re experiencing specific issues, such as error messages or non-responsive behavior?
2. The "پربازدیدترین اخبار" and "تازه‌ترین اخبار": The issue with the "پربازدیدترین اخبار" list has been resolved. I’ve checked and the display issue should no longer be present.
3. Header and Footer:

- Header/Footer Relevance: I’m not entirely clear on how the current header and footer aren't related to what we are. Could you provide more details on what changes are needed?
- YouTube Button: The YouTube button has been removed as requested.
- User Panel Button: The "صفحه کاربری" button is only visible to admins (you and me). It’s not shown to regular users. If you believe this should be handled differently or removed, please let me know.

4. Article Dates: For adjusting the dates of the two new essays, please specify the desired dates. You can edit the dates directly from the WordPress admin panel:

- Go to the "اخبار" section.
- Use the "ویرایش سریع" option for the post you want to update.
- Set the desired date in the provided field.

5. Logo Issues: I checked and the logo is already clickable and takes users to the home page.
6. Color and Branding: I suggest we create an issue to define a consistent color scheme for the website and the logo. This will ensure our branding is uniform across the site.

Please let me know if you need any further adjustments or have additional feedback. I’m on it and will make the necessary changes as quickly as possible.
