### ISSUE TITLE
Propose to Improve Documentation and Readme Files

### ISSUE THREAD

**Issue by BDadmehr0** [MedX-Media/MedX#16]
**Summary:**
I have reviewed the documentation and found some areas where it can be improved. Specifically, I noticed that the transition to a Google Docs file in the contribute section might not be ideal, and the Readme file could use some cleanup and enhancement. 

**Proposed Changes:**
- Enhance the Readme file with better formatting and additional features.
- Improve the contribute section to ensure it is complete and user-friendly.
- Possibly include the content of the Google Docs directly in the project for easier access and better version control.

**Benefits:**
- Improved clarity and accessibility of the documentation.
- Better onboarding experience for new contributors.
- More professional and polished project presentation.

**Next Steps:**
I would like to make these improvements and submit a pull request for review. Please let me know if this approach is acceptable.

**Questions:**
- Are there any specific guidelines or preferences for documentation improvements in this project?
- Should I follow any particular style guide or template for the Readme?

**Comment by aref-asadi** [comment]
We're thrilled to have you here and appreciate your willingness to help improve our project! Your proposed changes sound great and will undoubtedly enhance our documentation and contributor experience. Here’s how we can proceed:

1. Branch Management: Please make all your changes on the development branch. We only accept pull requests (PRs) to the main branch from development. Therefore, when creating your PR, make sure the head branch is your fork’s development, and the base branch is the development branch of the MedX repository. This helps maintain a clean workflow and ensures that all updates are properly reviewed and tested before merging into the main branch.

2. PR Submission: To help us review and merge your contributions efficiently:

- Keep PRs Focused: Each PR should address a specific issue or improvement with a manageable scope.
- Provide Descriptions: Include detailed descriptions in your PRs explaining the changes and their purpose. This helps us understand the context and facilitates a smoother review process.
- Avoid Deleting Files: If you need to delete files, please create an issue first and inform us so we can manage the deletions ourselves. This precaution ensures that ongoing work by other contributors is not disrupted.

Other than these guidelines, you are free to contribute wherever and however you wish.

**Comment by BDadmehr0** [comment]
We will definitely work with the mentioned method. The idea I have is to keep all the .MD files except the LICENSE.md and README.md and put the rest in the project wiki or in a directory.
