### ISSUE TITLE
Design Homepage

### ISSUE THREAD

**Issue by aref-asadi** [MedX-Media/MedX#2]
## Responsibility:
@aref-asadi 

## Deadline:
18 Aug 2024

## Description:
We need to design a homepage that effectively showcases the latest and most popular content. The layout should be user-friendly and visually appealing, ensuring easy navigation and access to key content.

## Homepage Requirements:

1. Banner for Latest Article:
- A 16:9 aspect ratio banner should be placed on the right side of the page and allocate 50% of the screen width to itself including the image of the latest article.
- inside the banner, display the title and metadata of the latest article, including the author, date, time of publication, and estimated reading time.

2. List of Top 3 Most Viewed Articles of the Month:
- On the left side, display a list of the top 3 most viewed articles of the month.
- Each article should include the title and metadata (author, date, and reading time).

3. Latest Articles Section:
- Below the banner and top articles, in the center of the page, display the latest articles.
- Articles should be presented in a grid layout with 3 columns and 5 rows.
- Each article should be shown as a card containing a 16:9 aspect ratio image, title, and metadata.

4. Pagination:
- Below the latest articles, include pagination to navigate through pages of articles grid.
- The pagination should include buttons for "First" and "Last" pages, "Next" and "Previous" pages, the current page number, and the numbers of the two pages before and after the current page.

## Tasks:
- [x] Design the homepage layout according to the above specifications. @aref-asadi 
- [x] Review the design. @Sinusealpha

**Comment by aref-asadi** [comment]
V.1:
[Homepage design](https://github.com/MedX-Media/MedX/blob/development/design/MedX_website_design-homepage.jpg)

**Comment by Sinusealpha** [comment]
thank you dear @aref-asadi. i saw your designs and i have some questions:

1. why did you decide to have before and after pages of content? i mean we just need 'x-1' and 'x-2' and etc. not 'x+1' and 'x+2' and etc. because the user wants to see the last contents and the next pages appear just after going to the previous pages. so we don't need it on the 'how page'. are we?

2. do you agree to have a border around the parts of the posts (to be like a box)? like what we have in GitHub. i mean some straight lines around each part of the design to be more comprehensible.

there is no more points about this design and you were very great. thank you.

**Comment by aref-asadi** [comment]
> thank you dear @aref-asadi. i saw your designs and i have some questions:
> 
> 1. why did you decide to have before and after pages of content? i mean we just need 'x-1' and 'x-2' and etc. not 'x+1' and 'x+2' and etc. because the user wants to see the last contents and the next pages appear just after going to the previous pages. so we don't need it on the 'how page'. are we?
> 
> 2. do you agree to have a border around the parts of the posts (to be like a box)? like what we have in GitHub. i mean some straight lines around each part of the design to be more comprehensible.
> 
> there is no more points about this design and you were very great. thank you.

Thank you for your review, Sina.

Regarding your first question, I didn't quite understand what you meant by the 'how page.' However, about the pagination, I thought that this way the user can have a better map of the content. For instance, if they're on page 5, they can know that there is also a page 7. I've felt this way on some websites that have this feature, and I found it pleasant. Additionally, I think it makes navigation easier. Usually, users remember the last 2 or 3 pages they visited, and they might want to jump from page 5 to page 3. Since I've experienced this myself, being able to jump two pages back with one click was enjoyable for me. Therefore, having access to the two previous and two next pages seemed like a good idea both for mapping and quick access.

As for your second question, I thought the simpler the design, the better it would be looked. Reducing graphical clutter makes it easier to focus on the content and text.

I am open to any new ideas that could improve the designs. If you have an idea that could enhance the design, please prepare it and share it with me so we can compare and decide better.

If you agree and find the designs functionally appropriate, we can use them as a basis to start implementation. Whenever you're ready with a second version of the design based on your ideas, we can review it.

**Comment by aref-asadi** [comment]
> 1- i'm sorry. that's not "how page". that's "home page".
> 
> 2- yes. you're correct when talking about pages 5 and 7. but on the home page, we're not on pages 5 and 7 and we're just on the 1st page.
> 
> 3- simpler design will always win. i also want to have simple ones with some borders to help users with better UIs.

Regarding pagination, I’m referring to the content displayed on the homepage, and I believe it would be better not to create a new page to display a list of content. Instead, everything should be done on a single page with just pagination.

As for the third point, I think having a border around the content is unnecessary and excessive. It would be better not to take inspiration from superhuman.ai in this matter because I actually disagree with their design and how they present their content.

**Comment by Sinusealpha** [comment]
1- what does that pagination mean? i couldn't understand your meaning.

2- their design isn't that good. but is much better than what we have right now, at least in my opinion. but after all, this is your responsibility and i just left my comment. do what you think is better.

**Comment by aref-asadi** [comment]
> 1- what does that pagination mean? i couldn't understand your meaning.
> 
> 2- their design isn't that good. but is much better than what we have right now, at least in my opinion. but after all, this is your responsibility and i just left my comment. do what you think is better.

1. I mean pagination for the content section (only the content section, not the whole page).

2. OK. This is just V.1. Of course, we will have more versions in the future.

**Comment by Sinusealpha** [comment]
1- i'm ok with it and i know that you're right about that list of content.

2- yes. i'm agree. we are gonna have a lot of +1% improvements. :)
