### ISSUE TITLE
Design Content page

### ISSUE THREAD

**Issue by aref-asadi** [MedX-Media/MedX#4]
## Responsibility:
@aref-asadi

## Deadline:
19 Aug 2024

## Description:
We need to design a content page that effectively presents content with related metadata and navigation options. The design should ensure clarity and ease of access to all relevant information.

## Content Page Requirements:

1. Content Metadata:
- Top Right: Display the article's subject, author’s name with their profile picture, publication date and time, and estimated reading time.
- Top Left: Display the article’s featured image.
2. Article Content: The main content of the article should be placed below the metadata and featured image.
3. Separator Line: A horizontal line should separate the article content from the subsequent sections.
4. Share Buttons: Below the separator line, include social media share buttons for users to share the article.
5. Additional Separator Line: A second horizontal line should be placed below the share buttons to separate them from the latest content section.
6. Latest content:
- At the bottom of the page, display a section for the latest content.
- Show the three most recent articles from the site, each with a featured image, title, and metadata (author, date, and time).

## Tasks:
- [x]  Design the layout of the content page according to the specifications. @aref-asadi 
- [x]  Review the design. @Sinusealpha

**Comment by aref-asadi** [comment]
V.1:
[Content page design](https://github.com/MedX-Media/MedX/blob/development/design/MedX_website_design-Content.jpg)

**Comment by Sinusealpha** [comment]
thank you @aref-asadi jan. that's amazing. but i'm gonna leave my comments in the next lines:

1. i'm deeply thinking about superhuman.ai's design for content and if you've seen it, they have borders for their text-contents and it helps users to see the content much better. that's somehow more beautiful. do you think that we should have those like borders for out text contents? if yes, please provide it.

2. i think that "سایر مطالب" you wrote under the text is somehow meaningless. because the user doesn't want to see other content. they probably want to see "latest" to "related" content and we should change this word.

3. i think that the design we made 2,3 weeks ago for the content of our website was somehow good enough to be used here and for the main picture of the post, it's metadata, etc, we can completely use that design and that's ok, if you agree.

there are no more points about this design in my opinion. that's good enough to be in the mtp and thank you again.

**Comment by aref-asadi** [comment]
> thank you @aref-asadi jan. that's amazing. but i'm gonna leave my comments in the next lines:
> 
> 1. i'm deeply thinking about superhuman.ai's design for content and if you've seen it, they have borders for their text-contents and it helps users to see the content much better. that's somehow more beautiful. do you think that we should have those like borders for out text contents? if yes, please provide it.
> 
> 2. i think that "سایر مطالب" you wrote under the text is somehow meaningless. because the user doesn't want to see other content. they probably want to see "latest" to "related" content and we should change this word.
> 
> 3. i think that the design we made 2,3 weeks ago for the content of our website was somehow good enough to be used here and for the main picture of the post, it's metadata, etc, we can completely use that design and that's ok, if you agree.
> 
> there are no more points about this design in my opinion. that's good enough to be in the mtp and thank you again.

Regarding the first point, I didn’t really like the layout and content of superhuman.ai. On each content page, there was a collection of different contents, arranged almost like a newspaper, and they used borders to separate them. Since we’ll only have one type of content per page, I thought there was no need for those borders. Instead, we can use separators to design and implement things more simply.

I agree with you on the second comment, and I think "Latest Content" would be a better replacement.

For the third comment, I tried to completely move away from previous designs and approach these designs with a simpler perspective. If you think a design change is needed, I’d be happy if you could prepare your suggestion and send it over so we can compare and decide better.

**Comment by Sinusealpha** [comment]
1- i'm agree with you aref jan. we don't have several contents on each page. but for that one content, we can use some borders. what's its problem?

2- thank you.

3- i'm ok with this design too. i told you that we can use our past design for blogs/news we made 2,3 weeks ago. do you remember that design? that was simple and good enough.

**Comment by aref-asadi** [comment]
> 1- i'm agree with you aref jan. we don't have several contents on each page. but for that one content, we can use some borders. what's its problem?
> 
> 2- thank you.
> 
> 3- i'm ok with this design too. i told you that we can use our past design for blogs/news we made 2,3 weeks ago. do you remember that design? that was simple and good enough.

Regarding the first point, I find it unnecessary and redundant, and I even disagree with its presence on the superhuman.ai website because each of its pages contains different sections, which forced them to include such borders. Considering that our content won’t be structured like that, I think it’s better to avoid these extra borders.

As for the third point, the previous design had a full-width structure, whereas the current theme of the new designs focuses on a centered, single-column layout that adapts better to different screen sizes. As a result, the previous design structurally contradicts the new designs and therefore cannot be used.

**Comment by Sinusealpha** [comment]
you're right. we just have one content in each page. but i have seen some websites with only one content on each page and also some borders. like motamem.ir.

so after all these discussions, i'm not a fan of borders :)) you're deciding and that was just an option. so thanks for considering.

**Comment by aref-asadi** [comment]
> you're right. we just have one content in each page. but i have seen some websites with only one content on each page and also some borders. like motamem.ir.
> 
> so after all these discussions, i'm not a fan of borders :)) you're deciding and that was just an option. so thanks for considering.

Thanks for your comment. So, let's start with this design and redesign it later. Maybe, you're right, or we both are wrong :).
