### ISSUE TITLE
Design Profile page

### ISSUE THREAD

**Issue by aref-asadi** [MedX-Media/MedX#6]
## Responsibility:
@aref-asadi

## Deadline:
19 Aug 2024

## Description:
We need to design a profile page for the MedX website where visitors can view detailed information about a user. This page will serve as a resume, showcasing the user’s contributions and activities within MedX. The layout should be clear and organized, allowing easy navigation through the user’s information.

## Profile Page Requirements:

1. Display the user’s profile picture and name at the top of the page.
2. Include the following sections, each separated by a horizontal line:
- Short Biography: A brief introduction of the user.
- About Me: A more detailed description of the user.
- Education: The user’s educational background.
- Experience: The user’s professional experiences.
- Skills: The user’s key skills.
- Activities: The user’s activities and involvement in relevant projects.
- Languages: Languages the user is proficient in.
- Published Contents: At the bottom of the page, display the articles published by the user on MedX.
The contents should be presented in a grid layout with 3 columns and 3 rows.
Include pagination below the grid, similar to the homepage, to navigate through more contents.

## Tasks:
- [x]  Design the layout of the profile page according to the specifications. @aref-asadi 
- [x]  Review. @Sinusealpha

**Comment by aref-asadi** [comment]
V.1:
[Profile page design](https://github.com/MedX-Media/MedX/blob/development/design/MedX_website_design-Profile_page.jpg)

**Comment by Sinusealpha** [comment]
thank you @aref-asadi for your design. but i think that we don't need this page for our mtp at all and we shouldn't deploy it in the next few days. we can think and discuss it for the next versions of our product and that's obviously not necessary for the upcoming launch. do you agree?

i should also add that designing this page is somehow a super-complex design and we should deal completely differently with it. that's not as simple as other pages we need for our mtp and i know that you can understand my words. if not, please tell me to provide more explanations.

thank you again for your efforts. that's invaluable for us!

**Comment by aref-asadi** [comment]
> thank you @aref-asadi for your design. but i think that we don't need this page for our mtp at all and we shouldn't deploy it in the next few days. we can think and discuss it for the next versions of our product and that's obviously not necessary for the upcoming launch. do you agree?
> 
> i should also add that designing this page is somehow a super-complex design and we should deal completely differently with it. that's not as simple as other pages we need for our mtp and i know that you can understand my words. if not, please tell me to provide more explanations.
> 
> thank you again for your efforts. that's invaluable for us!

I believe that we should at least consider this page for the initial authors, who are likely to be ourselves, so they can present themselves. We can also signal that we’ll be focusing more on this section in the future. I tried to keep this section as a basic resume so that the authors can introduce themselves.

In the future, we can also consider this section for users, and as you mentioned, we can have more discussions about its design and development. However, having this section, even in a simple form, in the initial version seems beneficial to me, as it will make people aware of its future existence. It will also help them see that their activity on our platform can be very useful for their personal branding.

**Comment by Sinusealpha** [comment]
i'm not agree. i think that by showing that "this is our resume", we are just signaling that we are here to show off. but i'm not disagree with it at all. i think we will implement this section in the future, but it's not necessary for the mtp. it's design isn't good and if i want to provide some comments on it, it can be many pages! so we need a totally new design for it and that's not a simple issue. please let us skip this section!

**Comment by aref-asadi** [comment]
> i'm not agree. i think that by showing that "this is our resume", we are just signaling that we are here to show off. but i'm not disagree with it at all. i think we will implement this section in the future, but it's not necessary for the mtp. it's design isn't good and if i want to provide some comments on it, it can be many pages! so we need a totally new design for it and that's not a simple issue. please let us skip this section!

One thing you might not be considering is that Superhuman.ai only has one author, and we can consider it as a personal blog at its current stage. Will we only have one author as well? Since we have multiple authors, won’t we need personal pages for them? And won’t we need user accounts for authors to manage their accounts and profiles?

**Comment by Sinusealpha** [comment]
yes. we may have several authors. but we now have them? who you're considering? :)) i can talk to some people to be our authors before launch. is that a good idea? what do you think? do you yourself want to be a writer?

so if we have several writers, we should have a page for each of them "in the future". we don't need it for launching an mtp. in the mtp stage, we just need a visual page like "medx writers" to show users that we have some writers. that's enough imo.

**Comment by aref-asadi** [comment]
> yes. we may have several authors. but we now have them? who you're considering? :)) i can talk to some people to be our authors before launch. is that a good idea? what do you think? do you yourself want to be a writer?
> 
> so if we have several writers, we should have a page for each of them "in the future". we don't need it for launching an mtp. in the mtp stage, we just need a visual page like "medx writers" to show users that we have some writers. that's enough imo.

Well, I understand you. So, let's talk about MTP in its issue.
