### ISSUE TITLE
preview of posts in telegram / bug

### ISSUE THREAD

**Issue by Sinusealpha** [MedX-Media/MedX#60]
responsible: @aref-asadi 
deadline: asap

description:
when we paste the link of a post from our website in telegram, we can not see its preview. we must fix it as soon as possible.

**Comment by BDadmehr0** [comment]
To enable link previews for your posts when shared on Telegram, you'll need to make sure that your website's metadata is set up correctly. Specifically, Telegram uses Open Graph tags and Twitter Card tags to generate link previews.

**Comment by BDadmehr0** [comment]
https://github.com/MedX-Media/MedX/pull/69

**Comment by aref-asadi** [comment]
Dear @BDadmehr0 solved this issue in [this PR](https://github.com/MedX-Media/MedX/pull/76)
