### ISSUE TITLE
Improper Display of Author Name and Image on Mobile View in Posts Page

### ISSUE THREAD

**Issue by aref-asadi** [MedX-Media/MedX#78]
In the mobile view of the posts page, the author’s name and image are not displayed properly. Instead of being aligned on a single line, they are shown incorrectly. Additionally, there is too much space between the post title and the author’s name and image.

### Expected Behavior:

- The author’s name and image should be displayed on the same line.
- The spacing between the title and the author’s name and image should be reduced.

### Required Fix:

- The CSS for responsive design needs to be updated to fix this issue.

### CSS File to Update:

- [CSS file](https://github.com/MedX-Media/MedX/blob/main/src%2Fmedx_website%2Fstatic%2Fcss%2Fstyles.css)

**Comment by vkkreddy45** [comment]
Hi aref-asadi, can you assign this to me?

**Comment by aref-asadi** [comment]
Hi, dear @vkkreddy45. Of course. We are grateful having your support and contribution.

**Comment by vkkreddy45** [comment]
<img width="1440" alt="Screenshot 2024-10-20 at 1 27 15 AM" src="https://github.com/user-attachments/assets/d85ec657-2699-4e5c-ad2c-9b16d1f8484b">

@aref-asadi , After setting everything up, I'm encountering an error when trying to run it locally, as shown in the attached file. I'm not sure what's causing it. Can you help me figure this out?

**Comment by BDadmehr0** [comment]
> <img alt="Screenshot 2024-10-20 at 1 27 15 AM" width="1440" src="https://private-user-images.githubusercontent.com/55943431/378160390-d85ec657-2699-4e5c-ad2c-9b16d1f8484b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NTA5NDksIm5iZiI6MTcyOTQ1MDY0OSwicGF0aCI6Ii81NTk0MzQzMS8zNzgxNjAzOTAtZDg1ZWM2NTctMjY5OS00ZTVjLWFkMmMtOWIxNmQxZjg0ODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE4NTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OWEyMzcxNTI2MTQwOWY3MDFkNDVhMmMyODBiMjBmZjQ3ODhmOTA5MzNkZGJhYjczNTcxMTBhNTQzMTM2MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eF1f5iZLGM8-oBg07swrdVp8FPPw_4K8hsQvSSW0TKU">
> 
> @aref-asadi , After setting everything up, I'm encountering an error when trying to run it locally, as shown in the attached file. I'm not sure what's causing it. Can you help me figure this out?

After cloning the Django project, please follow these steps to resolve error

1. **Migrate the database**:  
   Run the following command to apply migrations:
   ```bash
   python manage.py migrate
   ```

2. **Create a superuser**:  
   Create a superuser by running this command:
   ```bash
   python manage.py createsuperuser
   ```
   Fill in the fields as prompted and remember your username and password.

3. **Run the project**:  
   Start the Django development server:
   ```bash
   python manage.py runserver
   ```

4. **Access the admin page**:  
   Open your browser and navigate to the admin login page at:
   ```
   http://127.0.0.1:8000/admin
   ```

5. **Login and create a post**:  
   Log in using the superuser credentials you created, and create a post in the admin panel to avoid encountering issues on the home page (`/`).

**Comment by BDadmehr0** [comment]
https://github.com/MedX-Media/MedX/pull/91

**Comment by aref-asadi** [comment]
Hi dear @vkkreddy45 , we updated our CONTRIBUTING.md related to this problem. you can check it [here](https://github.com/MedX-Media/MedX/blob/main/CONTRIBUTING.md#want-to-contribute-to-website-development) and give us feedback.

**Comment by aref-asadi** [comment]
Thanks dear @BDadmehr0 for your support.

**Comment by aref-asadi** [comment]
Dear @BDadmehr0 solved this issue in [this PR](https://github.com/MedX-Media/MedX/pull/91).
