### ISSUE TITLE
Create Doc 'How to run this Django project locally' 

### ISSUE THREAD

**Issue by BDadmehr0** [MedX-Media/MedX#79]
I would like to request a detailed guide on how to run this Django project on my local machine. Could you please provide the following information?

1. **Project setup and dependencies:**
   - A list of all required dependencies (e.g., Python version, Django version, etc.)
   - How to install them (e.g., via `pip` or `requirements.txt`)
   
2. **Database setup:**
   - Instructions for setting up the database (e.g., using SQLite or PostgreSQL)
   - How to run migrations and populate the database with initial data (if applicable)

3. **Environment variables:**
   - A list of environment variables needed to run the project (if any)
   - How to configure them (e.g., `.env` file or system-level environment variables)

4. **Running the project:**
   - The command(s) needed to run the Django development server locally (e.g., `python manage.py runserver`)
   - Any additional steps to ensure the project runs correctly (e.g., creating superusers, setting permissions, etc.)

5. **Testing:**
   - Steps to run any tests (if there are automated tests in the project)
   - Instructions on how to ensure all functionality works as expected locally

6. **Common issues/troubleshooting:**
   - Any common errors that may occur and how to resolve them

**Comment by aref-asadi** [comment]
Hi dear @BDadmehr0 . I updated our CONTRIBUTING.md file with some changes about your suggestion to solve this issue. You can check it [here](https://github.com/MedX-Media/MedX/blob/main/CONTRIBUTING.md#want-to-contribute-to-website-development)
Thanks for your attention.
