### ISSUE TITLE
Design Login/Register page

### ISSUE THREAD

**Issue by aref-asadi** [MedX-Media/MedX#8]
## Responsibility:
@aref-asadi

## Deadline:
19 Aug 2024

## Description:
We need to design a login/register page where users can either log into their existing account or create a new one. The page should be intuitive and provide clear options for both actions.

## Login/register Page Requirements:

1. Register Form:
The register form should include the following fields:
- Username
- Email
- Password
There should be a "Register" button to submit the form and create a new account.

2. Login Form:
The login form should include the following fields:
- Username or Email
- Password
There should be a "Login" button to submit the form and access the user’s account.

3. Forgot Password:
Include a "Forgot Password" button that allows users to recover their password if they have forgotten it.

4. Conditional Navigation:
If the user is on the register page but already has an account, provide a link or button to redirect them to the login page.
Conversely, if the user is on the login page and doesn’t have an account, provide a link or button to redirect them to the register page.

## Tasks:
- [x]  Design the layout of the login/register page according to the specifications. @aref-asadi 
- [x]  Review. @Sinusealpha

**Comment by aref-asadi** [comment]
V.1:
[Login/Register page design](https://github.com/MedX-Media/MedX/blob/development/design/MedX_website_design-Login_Register_page.jpg)

**Comment by Sinusealpha** [comment]
thank you @aref-asadi. but do we need this login for the subscription? i think this is for later stages and that design is completely ok for the future. we also have implemented this login in the last versions of the website and i think there is no problem with that and we can just use that login, if you're ok.

**Comment by Sinusealpha** [comment]
i know. this is different from subscription and is so good! but isn't necessary for mtp launch and we should probably think about it after aug 22.

**Comment by aref-asadi** [comment]
> i know. this is different from subscription and is so good! but isn't necessary for mtp launch and we should probably think about it after aug 22.

Considering that we won’t have just one author, even in the MTP, I think having a registration and login page for our authors in the MTP will be necessary.

**Comment by Sinusealpha** [comment]
ok. i'm not thinking differently. but isn't it gonna be hard to implement in the next few days? can you afford it?

**Comment by aref-asadi** [comment]
> ok. i'm not thinking differently. but isn't it gonna be hard to implement in the next few days? can you afford it?

Well, let's discuss this in MTP issue.
